version: '3'
services:
  nginx:
    build: .
    image: 706353777632.dkr.ecr.ap-northeast-1.amazonaws.com/template/app:latest
    ports:
      - "80:80"
    logging:
      driver: awslogs
      options: 
        awslogs-group: template-nginx-logs
        awslogs-region: ap-northeast-1
        awslogs-stream-prefix: template-nginx-logs