version: '3'
services:
  nginx:
    build: .
    image: template/app:latest
    ports:
      - "80:80"
    logging:
      driver: awslogs
      options: 
        awslogs-group: nginx-service-01
        awslogs-region: ap-northeast-1
        awslogs-stream-prefix: nginx-service-01