version: '3'
services:
  nginx:
    build: .
    # 自分の環境で作成されたECRのARNを設定する
    image: 0000000000.dkr.ecr.ap-northeast-1.amazonaws.com/template/app:latest
    ports:
      - "80:80"
    logging:
      driver: awslogs
      options: 
        awslogs-group: template-nginx-logs
        awslogs-region: ap-northeast-1
        awslogs-stream-prefix: template-nginx-logs